create database mydb;
use mydb;

CREATE TABLE `DEPT` (
  `DEPTNO` SMALLINT NOT NULL AUTO_INCREMENT,
  `DNAME` VARCHAR(14) NULL DEFAULT NULL,
  `LOC` VARCHAR(13) NULL DEFAULT NULL,
  PRIMARY KEY (`DEPTNO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


CREATE TABLE `EMP` (
  `EMPNO` INT NOT NULL,
  `ENAME` VARCHAR(10) NULL DEFAULT NULL,
  `JOB` VARCHAR(9) NULL DEFAULT NULL,
  `HIREDATE` DATE NULL DEFAULT NULL,
  `SAL` DECIMAL(7,2) NULL DEFAULT NULL,
  `COMM` DECIMAL(7,2) NULL DEFAULT NULL,
  `DEPTNO` SMALLINT NOT NULL,
  PRIMARY KEY (`EMPNO`),
  INDEX `fk_EMP_DEPT_idx` (`DEPTNO` ASC),
  CONSTRAINT `fk_EMP_DEPT`
    FOREIGN KEY (`DEPTNO`)
    REFERENCES `mydb`.`DEPT` (`DEPTNO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;
